variable "avi_password" {}
variable "avi_username" {}
variable "vmc_vsphere_username" {}
variable "vmc_vsphere_password" {}
variable "vmc_vsphere_server" {}
variable "no_access_vcenter" {}
variable "vmc_sddc_id" {}
variable "vmc_org_id" {}
variable "vmc_nsx_token" {}
variable "vmc_nsx_server" {}
