- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Set variable avi_credentials without Avi version
      set_fact:
        avi_credentials: >
          {'controller': "{{ no_access_vcenter.avi_endpoint }}",
           'password': "{{ avi_password }}",
           'tenant': "{{ avi_tenant }}",
           'username': "{{ avi_username }}"}
      tags:
        - creds
      when:
        - no_access_vcenter.avi_endpoint is defined
        - avi_password is defined
        - avi_username is defined


    - add_host:
        hostname: avicontroller
        ansible_host: "{{ no_access_vcenter.avi_endpoint }}"
        ansible_port: 22
        ansible_user: "{{ avi_username }}"
        ansible_ssh_pass: "{{ avi_password }}"

    #### start of block

    - block:
        - name: Retrieve Avi Version Info
          avi_api_session:
            avi_credentials: "{{ avi_credentials | default(omit) }}"
            api_context: "{{ avi_api_context | default(omit) }}"
            http_method: get
            path: cluster/runtime
            params:
          register: cluster_results
          delegate_to: "localhost"

        - set_fact:
            se_master_ctl_version: "{{ cluster_results.obj.node_info.version.split('(')[0] }}"


        - name: Avi SE | Image deploy | Set SE image path for controller version < 18.2.6
          set_fact:
            se_image_path: "/opt/avi/se_ova"
          when:
            - se_master_ctl_version < "18.2.6"

      when:
        - no_access_vcenter.name is defined

    #### end of block

    #### start of block

    - block:
        - name: Retrieve Avi Version Info
          avi_api_session:
            avi_credentials: "{{ avi_credentials | default(omit) }}"
            api_context: "{{ avi_api_context | default(omit) }}"
            http_method: get
            path: "initial-data"
          register: data_res
          delegate_to: "localhost"

        - set_fact:
            se_master_ctl_version: "{{ cluster_results.obj.node_info.version.split('(')[0] }}"

        - name: Avi SE | Image deploy | Set SE image path for controller version >= 18.2.6
          set_fact:
            se_image_path: "/host/pkgs/{{ data_res.obj.version.Tag }}"
          when:
            - se_master_ctl_version >= "18.2.6"

      when:
        - no_access_vcenter.name is defined

    #### end of block

    - name: Set variable avi_credentials with Avi version
      set_fact:
        avi_credentials: >
          {'controller': "{{ no_access_vcenter.avi_endpoint }}",
           'password': "{{ avi_password }}",
           'username': "{{ avi_username }}",
           'tenant': "{{ avi_tenant }}",
           'api_version': "{{ se_master_ctl_version }}"}
      tags:
        - creds
      when:
        - no_access_vcenter.avi_endpoint is defined
        - avi_password is defined
        - avi_username is defined
        - se_master_ctl_version is defined

    - name:  Generate SE image on controller
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        tenant: "{{ avi_tenant }}"
        http_method: post
        path: 'fileservice/seova'
        timeout: 600
        data:
          file_format: ova
      delegate_to: localhost
      when:
        - no_access_vcenter.name is defined

- hosts: avicontroller
  gather_facts: yes

  tasks:

    - set_fact:
        se_image_path: "{{ hostvars['localhost']['se_image_path'] }}"

    - name: Download SE image
      fetch:
        src: "{{ se_image_path }}/se.ova"
        dest: ./
        flat: yes
        validate_checksum: False


- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Define ova path (in localhost variable)
      set_fact:
        ova_path: "./se.ova"
      when:
        - no_access_vcenter.name is defined

    - name: Get Clouds list
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        path: cloud
      register: cloudResults
      ignore_errors: yes

    - name: Define cloud uuid (in localhost variable)
      set_fact:
        cloud_no_access_vcenter_uuid: "{{ item.uuid }}"
      loop: "{{ cloudResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == no_access_vcenter.name

    - name: Add Content Library - Easy-Avi-CL-SE-NoAccess - import SE image
      shell: |
        export GOVC_DATACENTER="{{ no_access_vcenter.vcenter.dc }}"
        export GOVC_URL="https://{{ vsphere_username }}:{{ vsphere_password }}@{{ vsphere_server }}"
        export GOVC_DATASTORE="{{ no_access_vcenter.vcenter.datastore }}"
        export GOVC_INSECURE=true
        env | grep GOVC
        govc library.create Easy-Avi-CL-SE-NoAccess
        govc library.import Easy-Avi-CL-SE-NoAccess {{ ova_path }}
      when:
        - no_access_vcenter.vcenter.dc is defined
        - vsphere_username is defined
        - vsphere_password is defined
        - vsphere_server is defined
        - ova_path is defined

    - name: Run a playbook against SE group (SE Creation and SE Group Assignement) - this takes several minutes
      command: python3 python/seCreationVmware2.py "{{ avi_credentials | to_yaml }}" "{{ item | to_yaml }}" "{{ cloud_no_access_vcenter_uuid }}" "{{ no_access_vcenter.vcenter | to_yaml }}" "{{ vsphere_username }}" "{{ vsphere_password }}" "{{ vsphere_server }}" "Easy-Avi-CL-SE-NoAccess" "{{ no_access_vcenter.deployment_id }}"
      register: logPbSeCreation
      loop: "{{ no_access_vcenter.serviceEngineGroup }}"
      ignore_errors: yes
      when:
        - cloud_no_access_vcenter_uuid is defined
        - no_access_vcenter.serviceEngineGroup is defined
        - avi_credentials is defined
        - no_access_vcenter.vcenter is defined
        - vsphere_username is defined
        - vsphere_password is defined
        - vsphere_server is defined
        - no_access_vcenter.deployment_id is defined

    - name: Remove Content Library - Easy-Avi-CL-SE-NoAccess
      shell: |
        export GOVC_DATACENTER="{{ no_access_vcenter.vcenter.dc }}"
        export GOVC_URL="https://{{ vsphere_username }}:{{ vsphere_password }}@{{ vsphere_server }}"
        export GOVC_INSECURE=true
        env | grep GOVC
        govc library.rm Easy-Avi-CL-SE-NoAccess
      when:
        - no_access_vcenter.vcenter.dc is defined
        - vsphere_username is defined
        - vsphere_password is defined
        - vsphere_server is defined